# Travis CI (MIT License) configuration file for the ACF Content Blocks WP plugin
# @link https://travis-ci.org/

# Declare project language.
# @link http://about.travis-ci.org/docs/user/languages/php/
language: php

# Declare versions of PHP to use. Use one decimal max.
matrix:
  include:
    - php: 5.6
    - php: 7.1
    - php: 7.2
      env: SNIFF=1
    - php: 7.3

# Use this to prepare the system to install prerequisites or dependencies.
# e.g. sudo apt-get update.
# Failures in this section will result in build status 'errored'.
# before_install:

# Use this to prepare your build for testing.
# e.g. copy database configurations, environment variables, etc.
# Failures in this section will result in build status 'errored'.
before_script:
  - if [[ "$SNIFF" == "1" ]]; then composer self-update; fi
  - if [[ "$SNIFF" == "1" ]]; then composer install; fi
  - phpenv rehash

# Run test script commands.
# Default is specific to project language.
# All commands must exit with code 0 on success. Anything else is considered failure.
script:
  # Search for PHP syntax errors.
  - find . \( -name '*.php' \) | xargs -I file php -lf file
  # PHP Coding Standards
  - if [[ "$SNIFF" == "1" ]]; then vendor/bin/phpcs .; fi
